# Generated by Django 2.2.3 on 2019-07-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190720_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='stlfile',
            name='extra_files',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
