# Generated by Django 2.2.3 on 2019-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_mainfile_vertices_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfile',
            name='vertices_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
