# Generated by Django 2.2.3 on 2019-07-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190724_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='document',
            new_name='main_file',
        ),
    ]
