# Generated by Django 2.2.3 on 2019-07-18 14:23

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190716_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlfile',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='cms.Tagulous_STLFile_tags'),
        ),
    ]
