# Generated by Django 2.2.3 on 2019-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190731_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainfile',
            old_name='vertices_number',
            new_name='vertices',
        ),
        migrations.RemoveField(
            model_name='mainfile',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='mainfile',
            name='x',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='y',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='z',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
