# Generated by Django 2.2.3 on 2019-07-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20190724_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafile',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='cms.Entry'),
        ),
    ]
