# Generated by Django 2.2.3 on 2019-07-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20190731_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfile',
            name='vertices',
        ),
        migrations.AlterField(
            model_name='mainfile',
            name='x',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='mainfile',
            name='y',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='mainfile',
            name='z',
            field=models.FloatField(default=None),
        ),
    ]
