# Generated by Django 2.2.3 on 2019-07-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20190731_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfile',
            name='x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mainfile',
            name='y',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mainfile',
            name='z',
            field=models.FloatField(default=None, null=True),
        ),
    ]
