# Generated by Django 2.2.3 on 2019-07-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190731_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfile',
            name='vertices',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
