# Generated by Django 2.2.3 on 2019-07-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20190726_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='main_file',
        ),
    ]
