# Generated by Django 2.2.3 on 2019-07-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_mainfile_vertices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfile',
            name='vertices',
        ),
        migrations.RemoveField(
            model_name='mainfile',
            name='x',
        ),
        migrations.RemoveField(
            model_name='mainfile',
            name='y',
        ),
        migrations.RemoveField(
            model_name='mainfile',
            name='z',
        ),
    ]
