# Generated by Django 2.2.3 on 2019-07-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20190731_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfile',
            name='dimensions',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='vertices',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
