# Generated by Django 2.2.3 on 2019-07-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20190726_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
