# Generated by Django 2.2.3 on 2019-07-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_mainfile_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='mainfile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='mainfile',
            name='x_dims',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='y_dims',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='z_dims',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrafile',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='cms.Entry'),
        ),
    ]
