# Generated by Django 2.2.3 on 2019-07-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20190729_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfile',
            name='x_dims',
        ),
        migrations.RemoveField(
            model_name='mainfile',
            name='y_dims',
        ),
        migrations.RemoveField(
            model_name='mainfile',
            name='z_dims',
        ),
        migrations.AddField(
            model_name='mainfile',
            name='dims',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
