# Generated by Django 2.2.3 on 2019-08-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20190731_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfile',
            name='polgyons',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
