# Generated by Django 2.2.3 on 2019-07-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20190729_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfile',
            name='dims',
        ),
        migrations.AddField(
            model_name='mainfile',
            name='x_dims',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='y_dims',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='z_dims',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
