# Generated by Django 2.2.3 on 2019-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_mainfile_polgyons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfile',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='mainfile',
            name='x_axis',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='y_axis',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='z_axis',
            field=models.FloatField(default=None, null=True),
        ),
    ]
