# Generated by Django 2.2.3 on 2019-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20190801_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfile',
            name='polgyons',
            field=models.FloatField(default=None, null=True),
        ),
    ]
