# Generated by Django 2.2.3 on 2019-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20190801_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfile',
            name='polgyons',
        ),
        migrations.AddField(
            model_name='mainfile',
            name='polygons',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
