# Generated by Django 2.2.3 on 2019-08-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
