# Generated by Django 2.2.3 on 2019-07-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STLFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('path', models.URLField()),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
