# Generated by Django 2.2.3 on 2019-07-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190716_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stlfile',
            name='path',
        ),
    ]
