# Generated by Django 2.2.3 on 2019-07-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stlfile',
            name='document',
            field=models.FileField(default='t', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stlfile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stlfile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
